# ----
# Site

title: ATD文档中心
url: "https://juhe.baishancloud.com"
baseurl: "/docs"
google_analytics_key:
show_full_navigation: true

# -----
# Build

timezone: Etc/UTC

permalink: pretty

exclude:
  - README.md

collections:
  docs:
    title: Documentation
    permalink: /:path/
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: doc
  -
    scope:
      path: ""
      type: "docs"
    values:
      _options:
        content:
          width: 800
          height: 2000
  -
    scope:
      path: ""
      type: "posts"
    values:
      _comments:
        type: Marks the impact of this release

# -----------
# CloudCannon

types:
  - minor
  - major
